version: "3.8"

services:
  db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Sa123456
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      